version: "3.8"

x-env: &env
  PGID: 1001
  PUID: 1001
  UMASK: 002
  TZ: Asia/Kolkata

services:

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: unless-stopped
    network_mode: host
    depends_on:
      - postgres
    environment:
      <<: *env
    volumes:
      - /opt/appdata/home-assistant:/config

  postgres:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    user: 1001:1001
    shm_size: 128m
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - /opt/appdata/postgres/config.conf:/etc/postgresql/postgresql.conf
      - /opt/appdata/postgres/data:/var/lib/postgresql/data

  speedtest-tracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:latest-arm
    restart: unless-stopped
    ports:
      - 8700:80
    environment:
      <<: *env
      OOKLA_EULA_GDPR: true
    tmpfs:
      - /config/www:size=500m
      - /config/log:size=32m
    volumes:
      - /opt/appdata/speedtest-tracker/app:/config/www/app/Bin
      - /opt/appdata/speedtest-tracker:/config
