services:

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Kolkata
    volumes:
      - /opt/appdata/homeassistant:/config

  speedtesttracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:latest-arm
    restart: unless-stopped
    ports:
      - 8700:80
    environment:
      PGID: 1001
      PUID: 1001
      UMASK: 002
      TZ: Asia/Kolkata
      OOKLA_EULA_GDPR: true
    tmpfs:
      - /config/www:size=500m
      - /config/log:size=32m
    volumes:
      - /opt/appdata/speedtesttracker/app:/config/www/app/Bin
      - /opt/appdata/speedtesttracker:/config
