version: "3.8"
services:

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "localhost:8123", "-fso", "/dev/null"]
    volumes:
      - /opt/appdata/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      # MariaDB database socket
      - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  speedtest-tracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:latest-arm
    restart: unless-stopped
    ports:
      - 8700:80
    healthcheck:
      test: ["CMD", "curl", "localhost", "-fso", "/dev/null"]
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Asia/Kolkata
      - OOKLA_EULA_GDPR=true
    volumes:
      - /opt/appdata/speedtest-tracker:/config
      - type: tmpfs
        target: /config/log
        tmpfs:
          size: 32mb
      - type: tmpfs
        target: /config/www/node_modules
        tmpfs:
          size: 400mb
      - type: tmpfs
        target: /config/www/vendor
        tmpfs:
          size: 100mb
      - type: tmpfs
        target: /config/www/public
        tmpfs:
          size: 50mb
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
