version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-file: "5"
    max-size: "10m"

services:

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: unless-stopped
    logging: *default-logging
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "localhost:8123", "-fso", "/dev/null"]
    volumes:
      - /opt/appdata/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      # MariaDB database socket
      - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock
      # System sensors
      - /home/agneev/.homeassistant:/ssd:ro
      - /knox/.homeassistant:/knox:ro
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  speedtest-tracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:latest-arm
    restart: unless-stopped
    logging: *default-logging
    ports:
      - 8700:80
    healthcheck:
      test: ["CMD", "curl", "localhost", "-fso", "/dev/null"]
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Asia/Kolkata
      - OOKLA_EULA_GDPR=true
    volumes:
      - /opt/appdata/speedtest-tracker:/config
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
