x-timezone: &tz
  TZ: Asia/Kolkata

x-environment-vars: &env
  PUID: 1001
  PGID: 1001
  UMASK: 002
  <<: *tz
  
networks:
  media:
    external: true
  mqtt:
    external: true
  vlan:
    name: vlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.0.0.1/24
          gateway: 10.0.0.1
          ip_range: 10.0.0.80/28 # 10.0.0.80 - 10.0.0.95

services:

services:

  app:
    image: homeassistant/home-assistant
    restart: unless-stopped
    network_mode: "service:tailscale"
    environment:
      <<: *tz
    volumes:
      - ./:/config

  tailscale:
    image: lsiobase/alpine:edge
    restart: unless-stopped
    expose: ["80"]
    dns: 8.8.8.8
    networks:
      - media
      - mqtt
      - vlan
    environment:
      TAILSCALE_FUNNEL: on
      TAILSCALE_SERVE_PORT: 80
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_AUTHKEY: 
      TAILSCALE_HOSTNAME: home-assistant
      DOCKER_MODS: ghcr.io/tailscale-dev/docker-mod:main
      TAILSCALE_STATE_DIR: /config
      <<: *env
    volumes:
      - ./tailscale:/config
    labels:
      traefik.enable: true
      traefik.docker.network: media
      traefik.http.routers.hassio.rule: Host(`home-assistant.falcon.localcert.net`)
      traefik.http.routers.hassio.tls: true


  speedtesttracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:latest-arm
    restart: unless-stopped
    ports:
      - 8700:80
    environment:
      PGID: 1001
      PUID: 1001
      UMASK: 002
      TZ: Asia/Kolkata
      OOKLA_EULA_GDPR: true
    tmpfs:
      - /config/www:size=500m
      - /config/log:size=32m
    volumes:
      - /opt/appdata/speedtesttracker/app:/config/www/app/Bin
      - /opt/appdata/speedtesttracker:/config
