version: "3.8"

x-env: &env
  PGID: 1001
  PUID: 1001
  UMASK: 002
  TZ: Asia/Kolkata

x-labels: &pullio
  org.hotio.pullio.update: true
  org.hotio.pullio.notify: true
  org.hotio.pullio.discord.webhook: ${DISCORD_WEBHOOK}

services:

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "localhost:8123", "-fso", "/dev/null"]
    environment:
      <<: *env
    volumes:
      - /opt/appdata/home-assistant:/config
      - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock
    labels:
      <<: *pullio

  speedtest-tracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:latest-arm
    restart: unless-stopped
    ports:
      - 8700:80
    healthcheck:
      test: ["CMD", "curl", "localhost", "-fso", "/dev/null"]
    environment:
      <<: *env
      OOKLA_EULA_GDPR: true
    tmpfs:
      - /config/www:size=500m
      - /config/log:size=32m
    volumes:
      - /opt/appdata/speedtest-tracker/app:/config/www/app/Bin
      - /opt/appdata/speedtest-tracker:/config
    labels:
      traefik.http.routers.speedtest-tracker.rule: Host(`speedtest.always-on.nt`)
      <<: *pullio
