smart_home:
  endpoint: https://api.eu.amazonalexa.com/v3/events

  client_id: !secret alexa_client_id
  client_secret: !secret alexa_client_secret

  filter:
    include_entities:
      - media_player.bedroom_tv
      - media_player.old_room_tv
      - media_player.new_room_tv
      - switch.lofi_beats
      - switch.lofi_beats2

    include_domains:
      - climate
      - light
      - fan