smart_home:
  endpoint: https://api.eu.amazonalexa.com/v3/events

  client_id: !secret alexa_client_id
  client_secret: !secret alexa_client_secret

  filter:
    include_entities:
      - media_player.bedroom_tv
      - media_player.siti_cable_stb
      - media_player.old_room_tv
      - media_player.new_room_tv

    include_domains:
      - climate
      - light

  entity_config:
    media_player.siti_cable_stb:
      name: Cable box
