- platform: ping
  name: Node Ping
  host: 172.16.248.1
  count: 1
  scan_interval: 3
- platform: ping
  name: Cloudflare DNS Ping
  host: 1.1.1.1
  count: 1
  scan_interval: 3
- platform: ping
  name: Orbi Satellite Ping
  host: 10.0.0.2
  count: 1
  scan_interval: 10
- platform: ping
  name: Front Gate Camera Ping
  host: 10.0.0.20
  count: 1
  scan_interval: 5
