- platform: ping
  name: ISP Node ping
  host: 172.16.248.1
  count: 1
  scan_interval: 2
- platform: ping
  name: Cloudflare DNS ping
  host: 1.1.1.1
  count: 1
  scan_interval: 2
- platform: ping
  name: Orbi Satellite ping
  host: 10.0.0.2
  count: 1
  scan_interval: 10
- platform: ping
  name: Front gate camera ping
  host: 10.0.0.20
  count: 1
  scan_interval: 10
