alexa:
  filter:
    include_domains:
      - light
      - climate
    include_entities:
      - switch.lofi_beats
      - switch.lofi_beats2
      - switch.jazz_radio
      - media_player.bedroom_tv
      - switch.bedroom_ac_exhaust
    exclude_entities:
      - light.tv_lamp_2
google_actions:
  filter:
    exclude_entities:
      - light.tv_lamp_2
    include_domains:
      - light
      - climate
    include_entities:
      - media_player.bedroom_tv
      - switch.bedroom_ac_power
  entity_config:
    switch.bedroom_ac_power:
      name: Air Conditioner
      room: Bedroom
      aliases:
        - AC
    media_player.bedroom_tv:
      name: Television
      room: Bedroom
    climate.bedroom_ac:
      name: LG AirCon
      room: Bedroom
