int_qbt_alt_limit:
  command_on: "curl -s -o /dev/null http://10.0.0.11:8100/api/v2/transfer/toggleSpeedLimitsMode"
  command_off: "curl -s -o /dev/null http://10.0.0.11:8100/api/v2/transfer/toggleSpeedLimitsMode"
always_on_restart:
  command_on: "ssh -i ~/.ssh/pwd.key agneev@10.0.0.10 -t sudo reboot"
x200m_shutdown:
  command_on: "curl -X POST https://maker.ifttt.com/trigger/X200M_shutdown/with/key/xxxxx"
x200m_restart:
  command_on: "curl -X POST https://maker.ifttt.com/trigger/X200M_restart/with/key/xxxxx"
int_lofi_beats:
  command_on: "screen -S lofi -dm /usr/bin/omxplayer -o alsa $(youtube-dlc -g -f 95 5qap5aO4i9A)"
  command_off: "screen -S lofi -X quit"
int_lofi_beats2:
  command_on: "screen -S lofi2 -dm /usr/bin/omxplayer -o alsa $(youtube-dlc -g -f 95 DWcJFNfaw9c)"
  command_off: "screen -S lofi2 -X quit"
int_jazz_radio:
  command_on: "screen -S jazz_radio -dm /usr/bin/omxplayer -o alsa $(youtube-dl -g -f 95 fEvM-OUbaKs)"
  command_off: "screen -S jazz_radio -X quit"
