int_qbt_alt_limit:
  command_on: "curl -s -o /dev/null http://10.0.0.11:8100/api/v2/transfer/toggleSpeedLimitsMode"
  command_off: "curl -s -o /dev/null http://10.0.0.11:8100/api/v2/transfer/toggleSpeedLimitsMode"
x200m_shutdown:
  command_on: echo "x200m_shutdown" | netcat localhost 7900
x200m_restart:
  command_on: echo "x200m_restart" | netcat localhost 7900
int_lofi_beats:
  command_on: echo "lofi_on" | netcat localhost 7900
  command_off: echo "lofi_off" | netcat localhost 7900
int_lofi_beats2:
  command_on: echo "lofi2_on" | netcat localhost 7900
  command_off: echo "lofi2_off" | netcat localhost 7900
int_jazz_radio:
  command_on: echo "jazz_radio_on" | netcat localhost 7900
  command_off: echo "jazz_radio_off" | netcat localhost 7900
