always_on_restart:
  command_on: "ssh -i ~/.ssh/pwd.key agneev@10.0.0.10 -t sudo reboot"
x200m_shutdown:
  command_on: "curl -X POST https://maker.ifttt.com/trigger/X200M_shutdown/with/key/xxxxx"
x200m_restart:
  command_on: "curl -X POST https://maker.ifttt.com/trigger/X200M_restart/with/key/xxxxx"
int_lofi_beats:
  command_on: "/usr/bin/omxplayer -o alsa $(youtube-dl -g -f 95 5qap5aO4i9A) > /dev/null &"
  command_off: "pkill -u homeassistant -f omxplayer"
int_lofi_beats2:
  command_on: "/usr/bin/omxplayer -o alsa $(youtube-dl -g -f 95 DWcJFNfaw9c) > /dev/null &"
  command_off: "pkill -u homeassistant -f omxplayer"
int_jazz_radio:
  command_on: "/usr/bin/omxplayer -o alsa $(youtube-dl -g -f 95 UhxUpo8IH0o) > /dev/null &"
  command_off: "pkill -u homeassistant -f omxplayer"
