default_config:
shell_command:
  set_speaker_volume: "amixer -q set Headphone - '{{ states.input_number.speaker_volume.state | int}}'%"
input_number:
  speaker_volume:
    name: Speaker Volume
    min: 80
    max: 100
    icon: mdi:volume-high
sensor:
  - platform: history_stats
    name: int_internet_health
    entity_id: binary_sensor.cloudflare_dns_ping
    state: 'on'
    type: ratio
    end: '{{ now()}}'
    duration: 00:05:00
  - platform: qbittorrent
    name: qBt
    url: 'http://127.0.0.1:8100'
    username: !secret qbt_user
    password: !secret qbt_pass
    scan_interval: 30
  - platform: systemmonitor
    scan_interval: 120
    resources:
      - type: processor_temperature
  - platform: systemmonitor
    scan_interval: 60
    resources:
      - type: disk_use_percent
        arg: /home/agneev
      - type: disk_use_percent
        arg: /knox
      - type: disk_free
        arg: /knox
  - platform: systemmonitor
    scan_interval: 30
    resources:
      - type: processor_use
      - type: load_1m
  - platform: systemmonitor
    scan_interval: 15
    resources:
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
  - platform: tautulli
    api_key: !secret tautulli_api_key
    host: 127.0.0.1
    monitored_users:
      - agneev
  - platform: radarr
    host: 127.0.0.1
    api_key: !secret radarr_api_key
    days: 14
    monitored_conditions:
      - movies
      - commands
      - upcoming
switch:
  - platform: circadian_lighting
    disable_brightness_adjust: true
    lights_ct:
      - light.desk_light
    lights_rgb:
      - light.tv_lamp
device_tracker:
  - platform: netgear
    host: 10.0.0.1
    port: 80
    username: !secret netgear_user
    password: !secret netgear_pass
    new_device_defaults:
      track_new_devices: true
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_pass
      url: amazon.in
#android_ip_webcam:
#  - host: 10.0.0.70
#    scan_interval: 15
#    sensors:
#      - battery_level
#      - light
#      - motion
#    switches:
#      - motion_detect
#      - night_vision
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram
    allowed_chat_ids:
      - !secret telegram_chat_id
notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id
#weather:
#  - platform: darksky
#    api_key: !secret dark_sky
##############################
circadian_lighting:
wake_on_lan:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
webostv: !include webos.yaml
yeelight: !include yeelight.yaml
cloud: !include cloud.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
media_player: !include media_player.yaml
homekit: !include homekit.yaml
sensor command_line: !include cmd_sensor.yaml
light: !include light.yaml
sensor template: 
  platform: template
  sensors: !include template_sensor.yaml
switch template: 
  platform: template
  switches: !include template_switch.yaml
switch command_line: 
  platform: command_line
  switches: !include cmd_switch.yaml
#sensor restful: !include restful.yaml
discovery:
logger:
  default: error
homeassistant:
  customize: !include customize.yaml
frontend:
  themes: !include_dir_merge_named themes
tts:
  - platform: google_translate
logbook:
  exclude:
    entities:
      - binary_sensor.cloudflare_dns_ping
      - binary_sensor.node_ping
      - input_number.speaker_volume
recorder:
  auto_purge: false
  exclude:
    entities:
      - sensor.network_throughput_in_eth0
      - sensor.network_throughput_out_eth0
      - sensor.int_internet_health
      - sensor.load_1m
      - sensor.eth0_in_2
      - sensor.eth0_out_2
      - input_number.speaker_volume
