fan:
  - platform: smartir
    name: New Room Ceiling Fan
    unique_id: new_room_ceiling_fan
    device_code: 9000
    controller_data: remote.new_room_broadlink_rm4_mini_remote

  - platform: smartir
    name: Bedroom Ceiling Fan
    unique_id: bedroom_ceiling_fan
    device_code: 9000
    controller_data: remote.bedroom_broadlink_rm4_mini_remote

climate:
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 5000
    temperature_sensor: sensor.bedroom_temperature
    humidity_sensor: sensor.bedroom_humidity
    controller_data: remote.bedroom_broadlink_rm4_mini_remote

  - platform: smartir
    name: New Room AC
    unique_id: new_room_ac
    device_code: 6120
    temperature_sensor: sensor.new_room_temperature
    humidity_sensor: sensor.new_room_humidity
    controller_data: remote.new_room_broadlink_rm4_mini_remote

  - platform: smartir
    name: New Room AC 2
    unique_id: new_room_ac_2
    device_code: 6250
    temperature_sensor: sensor.new_room_temperature
    humidity_sensor: sensor.new_room_humidity
    controller_data: remote.new_room_broadlink_rm4_mini_remote

input_number:
  pi_volume:
    name: Soundbar Volume
    min: 0
    max: 100
    step: 1

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_chat_id

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/24
    - 100.102.123.68

logger:
  default: error

### YAML linked files

alexa: !include alexa.yaml
google_assistant: !include google_assistant.yaml
cloud: !include cloud.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml

binary_sensor:
  - platform: command_line
    command: if curl -s '10.10:9115/probe?target=8.8.8.8&module=icmp' | grep -q 'probe_success 1'; then echo ON; else echo OFF; fi
    name: Upstream DNS ping
    device_class: connectivity
    scan_interval: 3

  - platform: ping
    name: Orbi Satellite ping
    host: 10.0.0.2
    count: 1
    scan_interval: 10

  - platform: ping
    name: Front gate camera ping
    host: 10.0.0.20
    count: 1
    scan_interval: 10

media_player: !include media_player.yaml
light: !include light.yaml
group: []
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include shell_command.yaml
homeassistant:
  customize: !include customize.yaml

### Misc

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

recorder:
  db_url: sqlite:////config/database/home-assistant.db
  commit_interval: 5
  purge_keep_days: 28
  exclude:
    entities:
      - sensor.router_net_in
      - sensor.router_net_out

tts:
  - platform: google_translate
    language: en-us

default_config:
