climate:
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 5000
    temperature_sensor: sensor.broadlink_rm4_mini_temperature
    humidity_sensor: sensor.broadlink_rm4_mini_humidity
    controller_data: remote.broadlink_rm4_mini_remote

input_number:
  pi_volume:
    name: Soundbar Volume
    min: 0
    max: 100
    step: 5

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_pass
      url: amazon.in

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_chat_id

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/16
    - !secret public_proxied_ip
    - !secret oc1_tailscale_ip

logger:
  default: warn
#  logs:
#    homeassistant.components.netgear: debug

### YAML linked files

alexa: !include alexa.yaml
google_assistant: !include google_assistant.yaml
cloud: !include cloud.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
binary_sensor: !include binary_sensor.yaml
media_player: !include media_player.yaml
light: !include light.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# fan: !include fan.yaml
shell_command: !include shell_command.yaml
homeassistant:
  customize: !include customize.yaml

### Misc

frontend:
  themes: !include_dir_merge_named themes
recorder:
  db_url: !secret mysql_db
default_config:
