### TVs
media_player.old_room_tv:
  device_class: tv
  icon: mdi:television
media_player.new_room_tv:
  device_class: tv
  icon: mdi:television
media_player.bedroom_tv:
  device_class: tv
  icon: mdi:television
media_player.dining_hall_tv:
  device_class: tv
  icon: mdi:television
media_player.sony_bravia_tv:
  device_class: tv
  icon: mdi:television
### Lights
light.887444182cf43284aac9:
  supported_features: 63
light.tv_lamp:
  icon: mdi:alarm-light
light.desk_light:
  icon: mdi:desk-lamp
### Switches
switch.x200m_restart:
  icon: mdi:restart
switch.x200m_shutdown:
  icon: mdi:power
switch.always_on_restart:
  icon: mdi:restart
### Binary sensors
binary_sensor.remote_ui:
  icon: mdi:search-web
binary_sensor.node_ping:
  icon: mdi:office-building-marker
binary_sensor.cloudflare_dns_ping:
  icon: mdi:web
binary_sensor.updater:
  icon: mdi:home-assistant
binary_sensor.front_gate_camera_ping:
  icon: mdi:cctv
binary_sensor.orbi_satellite_ping:
  icon: mdi:access-point-network
### Sensors
sensor.hacs:
  name: HACS
  unit_of_measurement: updates
sensor.drive_used:
  icon: mdi:google-drive
sensor.qbt_down_speed:
  icon: mdi:arrow-down
sensor.qbt_up_speed:
  icon: mdi:arrow-up
sensor.eth0_out:
  icon: mdi:arrow-up
sensor.eth0_in:
  icon: mdi:arrow-down
sensor.eth0_out_2:
  icon: mdi:arrow-up
sensor.eth0_in_2:
  icon: mdi:arrow-down
sensor.speedtest_net_download_speed:
  icon: mdi:arrow-down
sensor.load_1m:
  unit_of_measurement: '1-min'
sensor.knox_free_percent:
  unit_of_measurement: '% free'
sensor.knox_state:
  icon: mdi:harddisk
sensor.drive_state:
  icon: mdi:google-drive
sensor.outdoor_humidity:
  icon: mdi:water-percent
# Camera
camera.front_gate_camera:
  icon: mdi:cctv
# Media Player
media_player.bedroom_echo:
  icon: mdi:amazon-alexa
media_player.new_room_echo:
  icon: mdi:amazon-alexa
media_player.everywhere:
  icon: mdi:amazon-alexa
media_player.ht_z9f_2:
  icon: mdi:speaker
