name: Home Assistant bridge
filter:
  include_domains:
    - sensor
    - switch
    - light
    - lock
    - climate
    - fan
    - humidifier
  include_entities:
    - script.reload_themes
  exclude_entities:
    - light.tv_lamp_2
    - sensor.processor_temperature
    - sensor.accuweather_realfeel_temperature
  exclude_entity_globs:
    - switch.int_*
    - switch.adaptive*
    - switch.new_room_echo*
    - switch.*_shutdown
    - switch.*_restart
entity_config:
  switch.16a_plug:
    type: outlet
  switch.6a_plug:
    type: outlet
  light.soundbar_volume:
    name: Soundbar
  switch.bedroom_ac_exhaust:
    name: AC Exhaust