- name: Home Assistant bridge

  filter:
    include_domains:
      - light
      - lock
      - climate
      - fan
      - humidifier

    include_entities:
      - sensor.old_room_echo_temperature
      - switch.reboot_orbi_satellite
      - switch.adaptive_lighting
      - switch.adaptive_lighting_sleep_mode_adaptive
      - sensor.broadlink_rm4_mini_humidity
      - binary_sensor.orbi_satellite_ping
      - media_player.siti_cable_stb
      - media_player.bedroom_mi_box_android

    include_entity_globs:
      - media_player.*echo
      - switch.lofi*
      - switch.*_plug

  entity_config:
    sensor.old_room_echo_temperature:
      name: Old Room Temperature
    media_player.bedroom_mi_box_android:
      name: Mi Box
    switch.adaptive_lighting_sleep_mode_adaptive:
      name: Sleep mode
    binary_sensor.orbi_satellite_ping:
      name: Orbi Satellite
    sensor.broadlink_rm4_mini_humidity:
      name: Bedroom Humidity
    light.soundbar_volume:
      name: Speakers
