- platform: template
  lights:
    color_flow:
      friendly_name: Color Flow
      icon_template: >-
        {% if is_state('light.tv_lamp','on') %} mdi:lightbulb-on
        {% else %} mdi:lightbulb {% endif %}
      value_template: >-
        {% if is_state('light.tv_lamp','on') %}
          {% if is_state_attr('light.tv_lamp','effect','Slowdown') %} true
          {% else %} false {% endif %}
        {% else %} false {% endif %}
      turn_on:
        - service: light.turn_on
          entity_id: light.tv_lamp
          data:
            effect: Slowdown
      turn_off:
        - service: light.turn_on
          entity_id: light.tv_lamp
          data:
            effect: Stop
    night_lamp:
      friendly_name: Night Lamp
      icon_template: mdi:power-sleep
      value_template: >-
        {% if is_state('light.tv_lamp','on') %}
          {% if state_attr('light.tv_lamp','brightness') < 30 %} true
          {% else %} false {% endif %}
        {% else %} false {% endif %}
      turn_on:
        - service: yeelight.set_color_scene
          data:
            entity_id: light.tv_lamp
            brightness: 10
            rgb_color:
              - 255
              - 0
              - 0
      turn_off:
        - service: light.turn_off
          entity_id: light.tv_lamp
    spotify_volume:
      friendly_name: Spotify Volume
      value_template: >-
        {% if is_state('media_player.spotify','playing') %}
          {% if state_attr('media_player.spotify','is_volume_muted') %} off
          {% else %} on {% endif %}
        {% else %} off {% endif %}
      turn_on:
        service: media_player.volume_mute
        data:
          entity_id: media_player.spotify
          is_volume_muted: false
      turn_off:
        service: media_player.volume_mute
        data:
          entity_id: media_player.spotify
          is_volume_muted: true
      set_level:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.spotify
          volume_level: "{{ (brightness/255*100) | int/100 }}"
      level_template: >-
        {% if is_state('media_player.spotify','playing') %}
          {{ (state_attr('media_player.spotify','volume_level')|float * 255)|int }}
        {% else %} 0 {% endif %}
    soundbar_volume:
      friendly_name: Soundbar Volume
      value_template: on
      turn_on:
        service: input_number.set_value
        data:
          entity_id: input_number.pi_volume
          value: 70
      turn_off:
        service: input_number.set_value
        data:
          entity_id: input_number.pi_volume
          value: 0
      set_level:
        service: input_number.set_value
        data_template:
          entity_id: input_number.pi_volume
          value: "{{ (brightness/2.55*100) | int/100 }}"
      level_template: "{{ (states('input_number.pi_volume')|float*2.55)|int }}"
