- platform: universal
  name: Sony Bravia TV
  state_template: >-
    {% if is_state('media_player.kd_55_ag', 'on') %} on
    {% else %} off {% endif %}
  children:
    - media_player.plex_plex_for_android_tv_sony_bravia
    - media_player.plex_mrmc_localhost
    - media_player.bravia_4k_gb_atv3
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.kd_55_ag
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: media_player.kd_55_ag
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.ht_z9f
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.ht_z9f
    select_source:
      service: media_player.select_source
      data_template:
        entity_id: media_player.kd_55_ag
        source: '{{ source }}'
    volume_set:
      service: media_player.volume_set
      data_template:
        entity_id: media_player.ht_z9f
        volume_level: '{{ volume_level }}'
  attributes:
    state: media_player.kd_55_ag
    is_volume_muted: media_player.ht_z9f|is_volume_muted
    volume_level: media_player.ht_z9f|volume_level
    source: media_player.bravia_4k_gb_atv3|app_name
    source_list: media_player.kd_55_ag|source_list
- platform: androidtv
  name: Dining Hall TV
  host: 10.0.0.64
#- platform: mpd
#  host: 127.0.0.1
