- platform: smartir
  name: Siti Cable STB
  unique_id: bedroom_cable_stb
  device_code: 1000
  controller_data: remote.broadlink_rm4_mini_remote
  power_sensor: media_player.bedroom_tv

- platform: androidtv
  name: Dining Hall TV
  host: 10.0.0.64
  device_class: firetv
  screencap: false
  exclude_unnamed_apps: true
