mute_pi:
  alias: Mute Pi
  sequence:
    - service: input_number.select_value 
      data:
        entity_id: input_number.pi_volume
        value: 0
skip:
  alias: skip
  mode: single
  sequence:
  - data_template:
      entity_id: '{{ entity }}'
      seek_position: '{{ state_attr(entity, ''media_position'') | float + interval
        }}'
    service: media_player.media_seek
  icon: mdi:fast-forward-30
spotify_dr_disrespect:
  alias: Spotify Dr Disrespect
  mode: single
  sequence:
  - data:
      shuffle: true
    entity_id: media_player.spotify
    service: media_player.shuffle_set
  - data:
      media_content_id: spotify:playlist:5IUxvS0U3ZL2NwKoybYEmD
      media_content_type: playlist
    entity_id: media_player.spotify
    service: media_player.play_media
  icon: mdi:spotify
spotify_lofi_beats:
  alias: Spotify lo-fi beats
  mode: single
  sequence:
  - data:
      shuffle: true
    entity_id: media_player.spotify
    service: media_player.shuffle_set
  - data:
      media_content_id: spotify:playlist:5FmmxErJczcrEwIFGIviYo
      media_content_type: playlist
    entity_id: media_player.spotify
    service: media_player.play_media
  icon: mdi:spotify
spotify_trending:
  alias: Spotify trending
  mode: single
  sequence:
  - data:
      shuffle: true
    entity_id: media_player.spotify
    service: media_player.shuffle_set
  - data:
      media_content_id: spotify:playlist:37i9dQZF1DXcBWIGoYBM5M
      media_content_type: playlist
    entity_id: media_player.spotify
    service: media_player.play_media
  icon: mdi:spotify
spotify_daily_mix_1:
  alias: Spotify Daily Mix 1
  mode: single
  sequence:
  - data:
      shuffle: true
    entity_id: media_player.spotify
    service: media_player.shuffle_set
  - data:
      media_content_id: spotify:playlist:xxxxx
      media_content_type: playlist
    entity_id: media_player.spotify
    service: media_player.play_media
  icon: mdi:spotify
spotify_daily_mix_2:
  alias: Spotify Daily Mix 2
  mode: single
  sequence:
  - data:
      shuffle: true
    entity_id: media_player.spotify
    service: media_player.shuffle_set
  - data:
      media_content_id: spotify:playlist:xxxxx
      media_content_type: playlist
    entity_id: media_player.spotify
    service: media_player.play_media
  icon: mdi:spotify
reload_themes:
  alias: HA - Reload themes
  mode: single
  sequence:
  - data: {}
    service: frontend.reload_themes
  icon: mdi:home-assistant
refresh_plex:
  alias: Refresh Plex
  sequence:
  - service: plex.refresh_library
    data:
      library_name: Movies
  - service: plex.refresh_library
    data:
      library_name: Movies (4K)
  - service: plex.refresh_library
    data:
      library_name: TV Shows
  mode: single
  icon: mdi:plex
