pi_volume_0: echo amixer_0 | nc localhost 7900
pi_volume_5: echo amixer_5 | nc localhost 7900
pi_volume_10: echo amixer_10 | nc localhost 7900
pi_volume_15: echo amixer_15 | nc localhost 7900
pi_volume_20: echo amixer_20 | nc localhost 7900
pi_volume_25: echo amixer_25 | nc localhost 7900
pi_volume_30: echo amixer_30 | nc localhost 7900
pi_volume_35: echo amixer_35 | nc localhost 7900
pi_volume_40: echo amixer_40 | nc localhost 7900
pi_volume_45: echo amixer_45 | nc localhost 7900
pi_volume_50: echo amixer_50 | nc localhost 7900
pi_volume_55: echo amixer_55 | nc localhost 7900
pi_volume_60: echo amixer_60 | nc localhost 7900
pi_volume_65: echo amixer_65 | nc localhost 7900
pi_volume_70: echo amixer_70 | nc localhost 7900
pi_volume_75: echo amixer_75 | nc localhost 7900
pi_volume_80: echo amixer_80 | nc localhost 7900
pi_volume_85: echo amixer_85 | nc localhost 7900
pi_volume_90: echo amixer_90 | nc localhost 7900
pi_volume_95: echo amixer_95 | nc localhost 7900
pi_volume_100: echo amixer_100 | nc localhost 7900
