pi_volume_0: echo amixer_0 | nc localhost 7900
pi_volume_1: echo amixer_1 | nc localhost 7900
pi_volume_2: echo amixer_2 | nc localhost 7900
pi_volume_3: echo amixer_3 | nc localhost 7900
pi_volume_4: echo amixer_4 | nc localhost 7900
pi_volume_5: echo amixer_5 | nc localhost 7900
pi_volume_6: echo amixer_6 | nc localhost 7900
pi_volume_7: echo amixer_7 | nc localhost 7900
pi_volume_8: echo amixer_8 | nc localhost 7900
pi_volume_9: echo amixer_9 | nc localhost 7900
pi_volume_10: echo amixer_10 | nc localhost 7900
pi_volume_11: echo amixer_11 | nc localhost 7900
pi_volume_12: echo amixer_12 | nc localhost 7900
pi_volume_13: echo amixer_13 | nc localhost 7900
pi_volume_14: echo amixer_14 | nc localhost 7900
pi_volume_15: echo amixer_15 | nc localhost 7900
pi_volume_16: echo amixer_16 | nc localhost 7900
pi_volume_17: echo amixer_17 | nc localhost 7900
pi_volume_18: echo amixer_18 | nc localhost 7900
pi_volume_19: echo amixer_19 | nc localhost 7900
pi_volume_20: echo amixer_20 | nc localhost 7900
pi_volume_21: echo amixer_21 | nc localhost 7900
pi_volume_22: echo amixer_22 | nc localhost 7900
pi_volume_23: echo amixer_23 | nc localhost 7900
pi_volume_24: echo amixer_24 | nc localhost 7900
pi_volume_25: echo amixer_25 | nc localhost 7900
pi_volume_26: echo amixer_26 | nc localhost 7900
pi_volume_27: echo amixer_27 | nc localhost 7900
pi_volume_28: echo amixer_28 | nc localhost 7900
pi_volume_29: echo amixer_29 | nc localhost 7900
pi_volume_30: echo amixer_30 | nc localhost 7900
pi_volume_31: echo amixer_31 | nc localhost 7900
pi_volume_32: echo amixer_32 | nc localhost 7900
pi_volume_33: echo amixer_33 | nc localhost 7900
pi_volume_34: echo amixer_34 | nc localhost 7900
pi_volume_35: echo amixer_35 | nc localhost 7900
pi_volume_36: echo amixer_36 | nc localhost 7900
pi_volume_37: echo amixer_37 | nc localhost 7900
pi_volume_38: echo amixer_38 | nc localhost 7900
pi_volume_39: echo amixer_39 | nc localhost 7900
pi_volume_40: echo amixer_40 | nc localhost 7900
pi_volume_41: echo amixer_41 | nc localhost 7900
pi_volume_42: echo amixer_42 | nc localhost 7900
pi_volume_43: echo amixer_43 | nc localhost 7900
pi_volume_44: echo amixer_44 | nc localhost 7900
pi_volume_45: echo amixer_45 | nc localhost 7900
pi_volume_46: echo amixer_46 | nc localhost 7900
pi_volume_47: echo amixer_47 | nc localhost 7900
pi_volume_48: echo amixer_48 | nc localhost 7900
pi_volume_49: echo amixer_49 | nc localhost 7900
pi_volume_50: echo amixer_50 | nc localhost 7900
pi_volume_51: echo amixer_51 | nc localhost 7900
pi_volume_52: echo amixer_52 | nc localhost 7900
pi_volume_53: echo amixer_53 | nc localhost 7900
pi_volume_54: echo amixer_54 | nc localhost 7900
pi_volume_55: echo amixer_55 | nc localhost 7900
pi_volume_56: echo amixer_56 | nc localhost 7900
pi_volume_57: echo amixer_57 | nc localhost 7900
pi_volume_58: echo amixer_58 | nc localhost 7900
pi_volume_59: echo amixer_59 | nc localhost 7900
pi_volume_60: echo amixer_60 | nc localhost 7900
pi_volume_61: echo amixer_61 | nc localhost 7900
pi_volume_62: echo amixer_62 | nc localhost 7900
pi_volume_63: echo amixer_63 | nc localhost 7900
pi_volume_64: echo amixer_64 | nc localhost 7900
pi_volume_65: echo amixer_65 | nc localhost 7900
pi_volume_66: echo amixer_66 | nc localhost 7900
pi_volume_67: echo amixer_67 | nc localhost 7900
pi_volume_68: echo amixer_68 | nc localhost 7900
pi_volume_69: echo amixer_69 | nc localhost 7900
pi_volume_70: echo amixer_70 | nc localhost 7900
pi_volume_71: echo amixer_71 | nc localhost 7900
pi_volume_72: echo amixer_72 | nc localhost 7900
pi_volume_73: echo amixer_73 | nc localhost 7900
pi_volume_74: echo amixer_74 | nc localhost 7900
pi_volume_75: echo amixer_75 | nc localhost 7900
pi_volume_76: echo amixer_76 | nc localhost 7900
pi_volume_77: echo amixer_77 | nc localhost 7900
pi_volume_78: echo amixer_78 | nc localhost 7900
pi_volume_79: echo amixer_79 | nc localhost 7900
pi_volume_80: echo amixer_80 | nc localhost 7900
pi_volume_81: echo amixer_81 | nc localhost 7900
pi_volume_82: echo amixer_82 | nc localhost 7900
pi_volume_83: echo amixer_83 | nc localhost 7900
pi_volume_84: echo amixer_84 | nc localhost 7900
pi_volume_85: echo amixer_85 | nc localhost 7900
pi_volume_86: echo amixer_86 | nc localhost 7900
pi_volume_87: echo amixer_87 | nc localhost 7900
pi_volume_88: echo amixer_88 | nc localhost 7900
pi_volume_89: echo amixer_89 | nc localhost 7900
pi_volume_90: echo amixer_90 | nc localhost 7900
pi_volume_91: echo amixer_91 | nc localhost 7900
pi_volume_92: echo amixer_92 | nc localhost 7900
pi_volume_93: echo amixer_93 | nc localhost 7900
pi_volume_94: echo amixer_94 | nc localhost 7900
pi_volume_95: echo amixer_95 | nc localhost 7900
pi_volume_96: echo amixer_96 | nc localhost 7900
pi_volume_97: echo amixer_97 | nc localhost 7900
pi_volume_98: echo amixer_98 | nc localhost 7900
pi_volume_99: echo amixer_99 | nc localhost 7900
pi_volume_100: echo amixer_100 | nc localhost 7900
