- platform: command_line
  switches:
    int_lofi_beats:
      command_on: echo lofi_on | nc localhost 7900
      command_off: echo lofi_off | nc localhost 7900

    int_lofi_beats2:
      command_on: echo lofi2_on | nc localhost 7900
      command_off: echo lofi2_off | nc localhost 7900

    int_the_good_life_radio:
      command_on: echo the_good_life_radio_on | nc localhost 7900
      command_off: echo the_good_life_radio_off | nc localhost 7900

    reboot_orbi_satellite:
      friendly_name: Reboot Orbi Satellite
      command_on: !secret reboot_orbi_satellite
      command_off: !secret reboot_orbi_satellite

- platform: template
  switches: 
    bedroom_ac_swing:
      friendly_name: Bedroom AC Swing
      icon_template: mdi:arrow-split-horizontal
      turn_on:
        - service: remote.send_command
          entity_id: remote.broadlink_rm4_mini_remote
          data:
            device: ac
            command: swing
      turn_off:
        - service: remote.send_command
          entity_id: remote.broadlink_rm4_mini_remote
          data:
            device: ac
            command: swing

    bedroom_ac_power:
      friendly_name: Bedroom AC Power
      value_template: "{{ not is_state('climate.bedroom_ac', 'off') }}"
      icon_template: mdi:air-conditioner
      turn_on:
        - service: climate.turn_on
          entity_id: climate.bedroom_ac
      turn_off:
        - service: climate.turn_off
          entity_id: climate.bedroom_ac

    lofi_beats:
      friendly_name: Lo-Fi Beats
      icon_template: mdi:music-circle
      value_template: "{{ is_state('input_boolean.lofi', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.lofi
        - service: switch.turn_on
          entity_id: switch.int_lofi_beats
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.lofi
        - service: switch.turn_off
          entity_id: switch.int_lofi_beats

    lofi_beats2:
      friendly_name: Lo-Fi Beats 2
      icon_template: mdi:music-circle-outline
      value_template: "{{ is_state('input_boolean.lofi2', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.lofi2
        - service: switch.turn_on
          entity_id: switch.int_lofi_beats2
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.lofi2
        - service: switch.turn_off
          entity_id: switch.int_lofi_beats2

    the_good_life_radio:
      friendly_name: The Good Life Radio
      icon_template: mdi:radio
      value_template: "{{ is_state('input_boolean.the_good_life_radio', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.the_good_life_radio
        - service: switch.turn_on
          entity_id: switch.int_the_good_life_radio
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.the_good_life_radio
        - service: switch.turn_off
          entity_id: switch.int_the_good_life_radio
