bedroom_echo_bt_speaker:
  friendly_name: Bedroom Echo Bluetooth Connect
  value_template: "{{ is_state('input_boolean.bedroom_echo_bluetooth_connected_state', 'on') }}"
  icon_template: mdi:speaker-bluetooth
  turn_on:
    - service: input_boolean.turn_on
      entity_id: input_boolean.bedroom_echo_bluetooth_connected_state
    - service: media_player.play_media
      entity_id: media_player.bedroom_echo
      data:
        media_content_id: 'connect to bluetooth speaker'
        media_content_type: custom
  turn_off:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_echo_bluetooth_connected_state
    - service: media_player.play_media
      entity_id: media_player.bedroom_echo
      data:
        media_content_id: 'disconnect from bluetooth speaker'
        media_content_type: custom
16a_plug:
  friendly_name: 16A Plug
  value_template: "{{ is_state('input_boolean.16a_plug_state', 'on') }}"
  icon_template: mdi:power-socket-uk
  turn_on:
    - service: input_boolean.turn_on
      entity_id: input_boolean.16a_plug_state
    - service: media_player.play_media
      entity_id: media_player.new_room_echo
      data:
        media_content_id: 'turn on Plug 33004ff8'
        media_content_type: custom
  turn_off:
    - service: input_boolean.turn_off
      entity_id: input_boolean.16a_plug_state
    - service: media_player.play_media
      entity_id: media_player.new_room_echo
      data:
        media_content_id: 'turn off Plug 33004ff8'
        media_content_type: custom
6a_plug:
  friendly_name: 6A Plug
  value_template: "{{ is_state('input_boolean.6a_plug_state', 'on') }}"
  icon_template: mdi:power-socket-uk
  turn_on:
    - service: input_boolean.turn_on
      entity_id: input_boolean.16a_plug_state
    - service: media_player.play_media
      entity_id: media_player.new_room_echo
      data:
        media_content_id: 'turn on Plug 340041f6'
        media_content_type: custom
  turn_off:
    - service: input_boolean.turn_off
      entity_id: input_boolean.6a_plug_state
    - service: media_player.play_media
      entity_id: media_player.new_room_echo
      data:
        media_content_id: 'turn off Plug 340041f6'
        media_content_type: custom
qbt_alt_limit:
  friendly_name: qBittorrent Alt Speeds
  availability_template: >-
    {% if not is_state('sensor.qbt_state','unavailable') %} true
    {% else %} false {% endif %}
  value_template: >-
    {% if is_state('sensor.qbittorrent_alt_limit_state','1') %} on
    {% else %} off {% endif %}
  icon_template: >-
    {% if is_state('switch.qbt_alt_limit','on') %} mdi:speedometer-slow
    {% else %} mdi:speedometer {% endif %}
  turn_on:
    - service: switch.turn_on
      entity_id: switch.int_qbt_alt_limit
  turn_off:
    - service: switch.turn_off
      entity_id: switch.int_qbt_alt_limit
bedroom_ac_exhaust:
  friendly_name: Bedroom AC Exhaust
  availability_template: >-
    {% if is_state('remote.broadlink_rm4_mini_remote', 'on') %} true
    {% else %} false {% endif %}
  value_template: >-
    {% if is_state('climate.bedroom_ac', 'fan_only') %} on
    {% else %} off {% endif %}
  icon_template: mdi:fan-chevron-up
  turn_on:
    - service: climate.set_hvac_mode
      entity_id: climate.bedroom_ac
      data:
        hvac_mode: fan_only
  turn_off:
    - service: climate.set_hvac_mode
      entity_id: climate.bedroom_ac
      data:
        hvac_mode: cool
bedroom_ac_swing:
  friendly_name: Bedroom AC Swing
  availability_template: >-
    {% if is_state('remote.broadlink_rm4_mini_remote', 'on') %} true
    {% else %} false {% endif %}
  icon_template: mdi:arrow-split-horizontal
  turn_on:
    - service: remote.send_command
      entity_id: remote.broadlink_rm4_mini_remote
      data:
        device: ac
        command: swing
  turn_off:
    - service: remote.send_command
      entity_id: remote.broadlink_rm4_mini_remote
      data:
        device: ac
        command: swing
bedroom_ac_fast_cool:
  friendly_name: Bedroom AC Fast Cool
  value_template: >-
    {% if is_state('climate.bedroom_ac','cool') %}
      {% if is_state_attr('climate.bedroom_ac','temperature',18) %}
        {% if is_state_attr('climate.bedroom_ac','fan_mode','high') %} on
        {% else %} off {% endif %}
      {% else %} off {% endif %}
    {% else %} off {% endif %}
  icon_template: mdi:weather-windy
  turn_on:
    - service: climate.set_temperature
      entity_id: climate.bedroom_ac
      data:
        temperature: 18
        hvac_mode: cool
    - service: climate.set_fan_mode
      entity_id: climate.bedroom_ac
      data:
        fan_mode: high
  turn_off:
    - service: climate.set_temperature
      entity_id: climate.bedroom_ac
      data:
        temperature: 21
    - service: climate.set_fan_mode
      entity_id: climate.bedroom_ac
      data:
        fan_mode: low
    - service: climate.turn_off
      entity_id: climate.bedroom_ac
bedroom_ac_power:
  friendly_name: Bedroom AC Power
  availability_template: >-
    {% if is_state('remote.broadlink_rm4_mini_remote', 'on') %} true
    {% else %} false {% endif %}
  value_template: >-
    {% if not is_state ('climate.bedroom_ac', 'unavailable') %}
      {% if not is_state ('climate.bedroom_ac', 'off') %} true
      {% else %} false {% endif %}
    {% else %} false {% endif %}
  icon_template: >-
    {% if not is_state('switch.ac_power', 'off') %}
      {% if is_state('climate.bedroom_ac', 'dry') %} mdi:water-percent
      {% elif is_state('climate.bedroom_ac', 'cool') %}
        {% if is_state_attr('climate.bedroom_ac','fan_mode','mid') %} mdi:fan-speed-2
        {% elif is_state_attr('climate.bedroom_ac','fan_mode','high') %} mdi:fan-speed-3
        {% else %} mdi:air-conditioner {% endif %}
      {% elif is_state('climate.bedroom_ac','fan_only') %}
        {% if is_state_attr('climate.bedroom_ac','fan_mode','auto') %} mdi:autorenew
        {% elif is_state_attr('climate.bedroom_ac','fan_mode','high') %} mdi:fan-chevron-up
        {% else %} mdi:fan {% endif %}
      {% else %} mdi:air-conditioner {% endif %}
    {% else %} mdi:air-conditioner {% endif %}
  turn_on:
    - service: climate.turn_on
      entity_id: climate.bedroom_ac
  turn_off:
    - service: climate.turn_off
      entity_id: climate.bedroom_ac
lofi_beats:
  friendly_name: Lo-Fi Beats
  icon_template: mdi:music-circle
  value_template: "{{ is_state('input_boolean.lofi', 'on') }}"
  turn_on:
    - service: input_boolean.turn_on
      entity_id: input_boolean.lofi
    - service: switch.turn_on
      entity_id: switch.int_lofi_beats
  turn_off:
    - service: input_boolean.turn_off
      entity_id: input_boolean.lofi
    - service: switch.turn_off
      entity_id: switch.int_lofi_beats
lofi_beats2:
  friendly_name: Lo-Fi Beats 2
  icon_template: mdi:music-circle-outline
  value_template: "{{ is_state('input_boolean.lofi2', 'on') }}"
  turn_on:
    - service: input_boolean.turn_on
      entity_id: input_boolean.lofi2
    - service: switch.turn_on
      entity_id: switch.int_lofi_beats2
  turn_off:
    - service: input_boolean.turn_off
      entity_id: input_boolean.lofi2
    - service: switch.turn_off
      entity_id: switch.int_lofi_beats2
jazz_radio:
  friendly_name: Jazz Radio
  icon_template: mdi:saxophone
  value_template: "{{ is_state('input_boolean.jazz_radio', 'on') }}"
  turn_on:
    - service: input_boolean.turn_on
      entity_id: input_boolean.jazz_radio
    - service: switch.turn_on
      entity_id: switch.int_jazz_radio
  turn_off:
    - service: input_boolean.turn_off
      entity_id: input_boolean.jazz_radio
    - service: switch.turn_off
      entity_id: switch.int_jazz_radio
