orbi_router_wan_in:
  friendly_name: Orbi Router WAN In
  value_template: "{{ (state_attr('sensor.orbi_router_vnstat_live','rx')['bytespersecond']|float/125000)|round(1) }}"
  icon_template: mdi:arrow-down
  unit_of_measurement: 'Mb/s'
orbi_router_wan_out:
  friendly_name: Orbi Router WAN Out
  value_template: "{{ (state_attr('sensor.orbi_router_vnstat_live','tx')['bytespersecond']|float/125000)|round(1) }}"
  icon_template: mdi:arrow-up
  unit_of_measurement: 'Mb/s'
orbi_router_wan_in_total:
  friendly_name: Orbi Router WAN In (total)
  value_template: >-
    {% if state_attr('sensor.orbi_router_vnstat_total','rx')|float/1000 != 0 %}
      {{ (state_attr('sensor.orbi_router_vnstat_total','rx')|float/1000)|round }}
    {% else %} missing {% endif %}
  icon_template: mdi:arrow-down
  unit_of_measurement: 'MB'
orbi_router_wan_out_total:
  friendly_name: Orbi Router WAN Out (total)
  value_template: >-
    {% if state_attr('sensor.orbi_router_vnstat_total','tx')|float/1000 != 0 %}
      {{ (state_attr('sensor.orbi_router_vnstat_total','tx')|float/1000)|round }}
    {% else %} missing {% endif %}
  icon_template: mdi:arrow-up
  unit_of_measurement: 'MB'
speedtest_net_upload_speed:
  friendly_name: Speedtest.net Upload Speed
  value_template: >-
    {{ (state_attr('sensor.speedtest_net_download_speed','upload')['bandwidth']|float/125000)|round(1) }}
  icon_template: mdi:arrow-up
  unit_of_measurement: 'Mb/s'
tautulli_total_bandwidth:
  friendly_name: Tautulli Total Bandwidth
  value_template: >-
    {% if state_attr('sensor.tautulli','total_bandwidth')|float/1024 < 1000 %}
      {{ (state_attr('sensor.tautulli','total_bandwidth')|float/1024)|round(1) }}
    {% else %} - {% endif %}
  icon_template: mdi:square-wave
  unit_of_measurement: 'Mb/s'
knox_free_percent:
  friendly_name: Knox free %
  value_template: "{{ 100 - states('sensor.disk_use_percent_knox')|int }}"
  icon_template: mdi:database
eth0_in:
  friendly_name: eth0 In
  value_template: "{{ (states('sensor.network_throughput_in_eth0')|float*8)|round(1) }}"
  unit_of_measurement: 'Mb/s'
eth0_out:
  friendly_name: eth0 Out
  value_template: "{{ (states('sensor.network_throughput_out_eth0')|float*8)|round(1) }}"
  unit_of_measurement: 'Mb/s'
