default_config:
discovery:
circadian_lighting:
homeassistant:
  customize: !include customize.yaml
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest
tts:
  - platform: google_translate
logger:
  default: warn
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor:
#  - platform: history_stats
#    name: Power Downtime
#    entity_id: device_tracker.front_gate_camera
#    state: 'off'
#    type: time
#    end: '{{ now()}}'
#    duration:
#      days: 30
  - platform: history_stats
    name: int_internet_health
    entity_id: binary_sensor.cloudflare_dns_ping
    state: 'on'
    type: ratio
    end: '{{ now()}}'
    duration: 00:05:00
#  - platform: pyload
#    host: 127.0.0.1
#    port: 7700
#    name: PyLoad
#    username: !secret pyload_user
#    password: !secret pyload_pass
  - platform: qbittorrent
    name: qBt
    url: 'http://127.0.0.1:8080'
    username: !secret qbt_user
    password: !secret qbt_pass
#  - platform: qbittorrent
#    name: qBt 2
#    url: 'http://:8080'
#    username:
#    password:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: disk_use_percent
        arg: /home/agneev
      - type: disk_use_percent
        arg: /merged
  - platform: tautulli
    api_key: !secret tautulli
    host: 127.0.0.1
    monitored_users:
      - agneev
  - platform: radarr
    host: 127.0.0.1
    api_key: !secret radarr
    days: 14
    monitored_conditions:
      - movies
      - upcoming
      - commands
switch:
  - platform: circadian_lighting
    disable_brightness_adjust: true
    lights_ct:
      - light.desk_light
    lights_rgb:
      - light.tv_lamp
#emulated_hue:
#  listen_port: 80
#  expose_by_default: false
#  entities:
#    switch.lofi_beats
#    switch.lofi_beats2
device_tracker:
  - platform: netgear
    host: 10.0.0.1
    port: 80
    username: !secret netgear_user
    password: !secret netgear_pass
    new_device_defaults:
      track_new_devices: true
#weather:
#  - platform: darksky
#    api_key: !secret dark_sky
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
#android_ip_webcam:
#  - host: 10.0.0.70
#    scan_interval: 15
#    sensors:
#      - battery_level
#      - light
#      - motion
#    switches:
#      - motion_detect
#      - night_vision
telegram_bot:
  - platform: polling
    api_key: !secret telegram
    allowed_chat_ids:
      - !secret telegram_chat_id
notify:
  - name: telegram_hassio
    platform: telegram
    chat_id: !secret telegram_chat_id
webostv: !include webostv.yaml
yeelight: !include yeelight.yaml
cloud: !include cloud.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
media_player: !include media_player.yaml
homekit: !include homekit.yaml
sensor command_line: !include cmd_sensor.yaml
light: !include light.yaml
sensor template:
  platform: template
  sensors: !include template_sensor.yaml
switch template:
  platform: template
  switches: !include template_switch.yaml
switch command_line:
  platform: command_line
  switches: !include cmd_switch.yaml
