---
name: "Hass.io config check"
on:
  push:
  pull_request:
    branches: [master]

jobs:
  check:
    name: Home Assistant Config Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Config Check
        uses: glitchcrab/action-hass-check-config@main
        with:
          config_path: config

